POST http://localhost:3003/user/create-user
Content-Type : application/json

{
    "user_id": "user_1",
	"values":{
	"fname":"sreejith",
	"lname":"t s",
	"phone":"8972472424",
	"email":"sreejith@gmail.com",
	"skills":["html","css","javascript"],
	"education":[
		{
			"institute": "GPC Perumbavoor",
			"education_type": "Diploma",
			"stream": "ECE",
			"marks":"56",
			"join_date": "12-8-2002",
			"end_date": "12-8-2002"
		}
	],
	"experience":[],
	"job_preferences":["Full Stack Developer","MERN Stack Developer"]
	}
}


###
GET http://localhost:3003/user/get-user/abss


###
POST http://localhost:3003/user/reject
Content-Type: application/json

{
    "job_id" : "6677c5d2e333220c8bed921b",
    "user_id": "_EDxD8v1JrMWz_K00AjS"
}


###
POST http://localhost:3003/user/update-info
Content-Type: application/json

{
	"data":{
		"lname":"Conan",
	},
	"user_id":"_EDxD8v1JrMWz_K00AjS"
}



###
POST http://localhost:3003/user/remove-education
Content-Type: application/json

{
	"education":{
		"_id" : "66745385eb42086b7993cf38"
	},
	"user_id":"_EDxD8v1JrMWz_K00AjS"
}


###
POST http://localhost:3003/user/save-job
Content-Type: application/json

{
	"user_id":"asdasdas",
	"job_id":"kjkj"
}


###
PATCH http://localhost:3003/user/unsave
Content-Type: application/json

{
	"user_id":"asdasdas",
	"job_id":"kjkj"
}