import express from "express";
import { createUser } from "./controllers/createUser.js";
import { getUser } from "./controllers/getUser.js";
import { getJob } from "./controllers/getJob.js";
import { addEducation } from "./controllers/user-data/add/addEducation.js";
import { addProject } from "./controllers/user-data/add/addProjects.js";
import { addExperience } from "./controllers/user-data/add/addExperience.js";
import { updateInfo } from "./controllers/user-data/update/update-info.js";
import { updateEducation } from "./controllers/user-data/update/updateEducation.js";
import { updateExperience } from "./controllers/user-data/update/updateExperience.js";
import { updateProjects } from "./controllers/user-data/update/updateProjects.js";
import { removeEducation } from "./controllers/user-data/remove/removeEducation.js";
import { removeExperience } from "./controllers/user-data/remove/removeExperience.js";
import { removeProjects } from "./controllers/user-data/remove/removeProjects.js";
import { updateSkills } from "./controllers/user-data/update/update-skills.js";
import { updatePreferences } from "./controllers/user-data/update/updatePreferences.js";
import { updatePhone } from "./controllers/user-data/update/updatePhone.js";
import { saveJob } from "./controllers/saveJob.js";
import { removeSaved } from "./controllers/removeSaved.js";
import { getSavedJobs } from "./controllers/getSavedJobs.js";
import { appliedJobs } from "./controllers/getAppliedJobs.js";
import { updateUserAvatar } from "./controllers/user-data/update/updateUserAvatar.js";
import { authentication } from "./middleware/authentication.js";

const router = express.Router();

router.get("/get-user/:id", getUser);
router.get("/get-job/:id/:uid", authentication, getJob);
router.get("/saved/:id", authentication, getSavedJobs);
router.get("/get-applied-jobs/:id", authentication, appliedJobs);
router.post("/create-user", createUser);
router.post("/add-education", authentication, addEducation);
router.post("/add-experience", authentication, addExperience);
router.post("/add-projects", authentication, addProject);
router.post("/update-info", authentication, updateInfo);
router.post("/update-skills", authentication, updateSkills);
router.post("/update-preferences", authentication, updatePreferences);
router.post("/update-phone", authentication, updatePhone);
router.post("/update-education", authentication, updateEducation);
router.post("/update-experience", authentication, updateExperience);
router.post("/update-project", authentication, updateProjects);
router.post("/remove-education", authentication, removeEducation);
router.post("/remove-experience", authentication, removeExperience);
router.post("/remove-projects", authentication, removeProjects);
router.post("/save-job", authentication, saveJob);
router.post("/update-avatar", authentication, updateUserAvatar);
router.patch("/unsave", authentication, removeSaved);

export default router;
